# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 21:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 29, 21, 40, 14, 508216)),
        ),
    ]
