# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='datetime',
        ),
        migrations.AddField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 3, 35, 51, 724640)),
        ),
        migrations.AddField(
            model_name='post',
            name='last_modified_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 3, 35, 51, 724734)),
        ),
    ]
