# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 22:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20170630_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 4, 13, 22, 746812)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 30, 4, 13, 22, 746890)),
        ),
    ]
