# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 13:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_auto_20170706_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='numberofcomments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 18, 49, 35, 968611)),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 18, 49, 35, 967575)),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified_on',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 6, 18, 49, 35, 967650)),
        ),
    ]
